version: '3.9'

services:
  spotkick:
    container_name: spotkick
    build: .
    depends_on:
      - spotkick-data
    ports:
      - "6254:5000"
#    environment:
#      SPOTKICK_Spotify.ClientId: <REPLACE_ME>
#      SPOTKICK_Spotify.ClientSecret: <REPLACE_ME>
#      SPOTKICK_Spotify.CallbackUrl: <REPLACE_ME>
#      SPOTKICK_Songkick.Key: <REPLACE_ME>
  spotkick-data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: spotkick-data
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4SSW0RD!