version: '3.4'

services:
  spotkick:
    image: ${DOCKER_REGISTRY}spotkick
    build:
      context: .
      dockerfile: Spotkick/Dockerfile
    ports:
      - "32768:80"
  spotkick-data:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4SSW0RD!